drop policy "notification_read" on "public"."notifications";

alter type "public"."NotificationType" rename to "NotificationType__old_version_to_be_dropped";

create type "public"."NotificationType" as enum ('report', 'news', 'notification', 'survey');

create table "public"."surveyAnswers" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "updatedAt" timestamp with time zone not null,
    "survey" bigint not null,
    "surveyQuestion" bigint not null,
    "organisation" text not null,
    "answer" text,
    "user" uuid,
    "userLanguage" "Language" not null,
    "questionType" text not null,
    "answerIndex" smallint not null
);


alter table "public"."surveyAnswers" enable row level security;

create table "public"."surveyInvitations" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "updatedAt" timestamp with time zone not null default now(),
    "user" uuid not null,
    "survey" bigint not null,
    "isFinished" boolean not null,
    "organisation" text not null
);


alter table "public"."surveyInvitations" enable row level security;

create table "public"."surveyQuestions" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "updatedAt" timestamp with time zone not null default now(),
    "survey" bigint not null,
    "en" jsonb not null,
    "ru" jsonb not null,
    "kaz" jsonb not null,
    "image" text,
    "type" text not null,
    "isRequired" boolean not null,
    "organisation" text
);


alter table "public"."surveyQuestions" enable row level security;

alter table "public"."notifications" alter column type type "public"."NotificationType" using type::text::"public"."NotificationType";

drop type "public"."NotificationType__old_version_to_be_dropped";

alter table "public"."surveys" drop column "created_at";

alter table "public"."surveys" add column "createdAt" timestamp with time zone not null default now();

alter table "public"."surveys" add column "creator" uuid not null;

alter table "public"."surveys" add column "deadline" timestamp with time zone;

alter table "public"."surveys" add column "description" jsonb not null;

alter table "public"."surveys" add column "displayId" text not null;

alter table "public"."surveys" add column "doneCount" bigint not null;

alter table "public"."surveys" add column "invitedCount" bigint not null;

alter table "public"."surveys" add column "name" jsonb not null;

alter table "public"."surveys" add column "organisation" text not null;

alter table "public"."surveys" add column "status" text not null;

alter table "public"."surveys" add column "updatedAt" timestamp with time zone not null;

alter table "public"."surveys" enable row level security;

alter table "public"."users" add column "resetPasswordCode" text;

alter table "public"."users" add column "resetPasswordCodeExpireTime" timestamp with time zone;

CREATE UNIQUE INDEX "surveyAnswers_pkey" ON public."surveyAnswers" USING btree (id);

CREATE UNIQUE INDEX "surveyInvitations_pkey" ON public."surveyInvitations" USING btree (id);

CREATE UNIQUE INDEX "surveyQuestions_pkey" ON public."surveyQuestions" USING btree (id);

alter table "public"."surveyAnswers" add constraint "surveyAnswers_pkey" PRIMARY KEY using index "surveyAnswers_pkey";

alter table "public"."surveyInvitations" add constraint "surveyInvitations_pkey" PRIMARY KEY using index "surveyInvitations_pkey";

alter table "public"."surveyQuestions" add constraint "surveyQuestions_pkey" PRIMARY KEY using index "surveyQuestions_pkey";

alter table "public"."surveyAnswers" add constraint "public_surveyAnswers_organisation_fkey" FOREIGN KEY (organisation) REFERENCES organisations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."surveyAnswers" validate constraint "public_surveyAnswers_organisation_fkey";

alter table "public"."surveyAnswers" add constraint "public_surveyAnswers_surveyId_fkey" FOREIGN KEY (survey) REFERENCES surveys(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."surveyAnswers" validate constraint "public_surveyAnswers_surveyId_fkey";

alter table "public"."surveyAnswers" add constraint "public_surveyAnswers_surveyQuestionId_fkey" FOREIGN KEY ("surveyQuestion") REFERENCES "surveyQuestions"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."surveyAnswers" validate constraint "public_surveyAnswers_surveyQuestionId_fkey";

alter table "public"."surveyAnswers" add constraint "public_surveyAnswers_user_fkey" FOREIGN KEY ("user") REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."surveyAnswers" validate constraint "public_surveyAnswers_user_fkey";

alter table "public"."surveyInvitations" add constraint "public_surveyInvitations_organisation_fkey" FOREIGN KEY (organisation) REFERENCES organisations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."surveyInvitations" validate constraint "public_surveyInvitations_organisation_fkey";

alter table "public"."surveyInvitations" add constraint "public_surveyInvitations_survey_fkey" FOREIGN KEY (survey) REFERENCES surveys(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."surveyInvitations" validate constraint "public_surveyInvitations_survey_fkey";

alter table "public"."surveyInvitations" add constraint "public_surveyInvitations_user_fkey" FOREIGN KEY ("user") REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."surveyInvitations" validate constraint "public_surveyInvitations_user_fkey";

alter table "public"."surveyQuestions" add constraint "public_surveyQuestions_organisation_fkey" FOREIGN KEY (organisation) REFERENCES organisations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."surveyQuestions" validate constraint "public_surveyQuestions_organisation_fkey";

alter table "public"."surveyQuestions" add constraint "public_surveyQuestions_survey_fkey" FOREIGN KEY (survey) REFERENCES surveys(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."surveyQuestions" validate constraint "public_surveyQuestions_survey_fkey";

alter table "public"."surveys" add constraint "public_surveys_creator_fkey" FOREIGN KEY (creator) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."surveys" validate constraint "public_surveys_creator_fkey";

alter table "public"."surveys" add constraint "public_surveys_organisation_fkey" FOREIGN KEY (organisation) REFERENCES organisations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."surveys" validate constraint "public_surveys_organisation_fkey";

create or replace view "public"."usersManagement" as  SELECT u.id,
    u."lastLogin",
    u."applicationRole",
    u.organisation,
    u.status,
    u."loginMethod",
    up.name,
    up."idNumber",
    up."jobTitle",
    up."smallPhotoUrl",
    up.email,
    up."mobileNumber",
    r.name AS role,
    us.company,
    lower(up.name) AS "orderName",
    lower(up."jobTitle") AS "orderJobTitle",
    lower(us.company) AS "orderCompany",
    lower(r.name) AS "orderRole",
    lower(((((((((((up.name || ' '::text) || up."idNumber") || ' '::text) || up."jobTitle") || ' '::text) || up.email) || ' '::text) || up."mobileNumber") || ' '::text) || us.company)) AS search,
    up."profileRating",
    up."photoUrl",
    up."employmentType"
   FROM (((users u
     JOIN "userProfiles" up ON ((u.id = up.id)))
     JOIN roles r ON ((u.role = r.id)))
     JOIN "userStructures" us ON ((u.id = us.id)));


grant delete on table "public"."surveyAnswers" to "anon";

grant insert on table "public"."surveyAnswers" to "anon";

grant references on table "public"."surveyAnswers" to "anon";

grant select on table "public"."surveyAnswers" to "anon";

grant trigger on table "public"."surveyAnswers" to "anon";

grant truncate on table "public"."surveyAnswers" to "anon";

grant update on table "public"."surveyAnswers" to "anon";

grant delete on table "public"."surveyAnswers" to "authenticated";

grant insert on table "public"."surveyAnswers" to "authenticated";

grant references on table "public"."surveyAnswers" to "authenticated";

grant select on table "public"."surveyAnswers" to "authenticated";

grant trigger on table "public"."surveyAnswers" to "authenticated";

grant truncate on table "public"."surveyAnswers" to "authenticated";

grant update on table "public"."surveyAnswers" to "authenticated";

grant delete on table "public"."surveyAnswers" to "service_role";

grant insert on table "public"."surveyAnswers" to "service_role";

grant references on table "public"."surveyAnswers" to "service_role";

grant select on table "public"."surveyAnswers" to "service_role";

grant trigger on table "public"."surveyAnswers" to "service_role";

grant truncate on table "public"."surveyAnswers" to "service_role";

grant update on table "public"."surveyAnswers" to "service_role";

grant delete on table "public"."surveyInvitations" to "anon";

grant insert on table "public"."surveyInvitations" to "anon";

grant references on table "public"."surveyInvitations" to "anon";

grant select on table "public"."surveyInvitations" to "anon";

grant trigger on table "public"."surveyInvitations" to "anon";

grant truncate on table "public"."surveyInvitations" to "anon";

grant update on table "public"."surveyInvitations" to "anon";

grant delete on table "public"."surveyInvitations" to "authenticated";

grant insert on table "public"."surveyInvitations" to "authenticated";

grant references on table "public"."surveyInvitations" to "authenticated";

grant select on table "public"."surveyInvitations" to "authenticated";

grant trigger on table "public"."surveyInvitations" to "authenticated";

grant truncate on table "public"."surveyInvitations" to "authenticated";

grant update on table "public"."surveyInvitations" to "authenticated";

grant delete on table "public"."surveyInvitations" to "service_role";

grant insert on table "public"."surveyInvitations" to "service_role";

grant references on table "public"."surveyInvitations" to "service_role";

grant select on table "public"."surveyInvitations" to "service_role";

grant trigger on table "public"."surveyInvitations" to "service_role";

grant truncate on table "public"."surveyInvitations" to "service_role";

grant update on table "public"."surveyInvitations" to "service_role";

grant delete on table "public"."surveyQuestions" to "anon";

grant insert on table "public"."surveyQuestions" to "anon";

grant references on table "public"."surveyQuestions" to "anon";

grant select on table "public"."surveyQuestions" to "anon";

grant trigger on table "public"."surveyQuestions" to "anon";

grant truncate on table "public"."surveyQuestions" to "anon";

grant update on table "public"."surveyQuestions" to "anon";

grant delete on table "public"."surveyQuestions" to "authenticated";

grant insert on table "public"."surveyQuestions" to "authenticated";

grant references on table "public"."surveyQuestions" to "authenticated";

grant select on table "public"."surveyQuestions" to "authenticated";

grant trigger on table "public"."surveyQuestions" to "authenticated";

grant truncate on table "public"."surveyQuestions" to "authenticated";

grant update on table "public"."surveyQuestions" to "authenticated";

grant delete on table "public"."surveyQuestions" to "service_role";

grant insert on table "public"."surveyQuestions" to "service_role";

grant references on table "public"."surveyQuestions" to "service_role";

grant select on table "public"."surveyQuestions" to "service_role";

grant trigger on table "public"."surveyQuestions" to "service_role";

grant truncate on table "public"."surveyQuestions" to "service_role";

grant update on table "public"."surveyQuestions" to "service_role";

create policy "surveys_read"
on "public"."surveyAnswers"
as permissive
for select
to authenticated
using ((isuseradmin(auth.uid()) OR (isuserinorg(organisation, auth.uid()) AND ((((getuserpermissionsobject(auth.uid(), 'surveys'::text))::json #> '{default}'::text[]) ->> 'read'::text))::boolean)));


create policy "surveys_read"
on "public"."surveyInvitations"
as permissive
for select
to authenticated
using ((isuseradmin(auth.uid()) OR (isuserinorg(organisation, auth.uid()) AND ((((getuserpermissionsobject(auth.uid(), 'surveys'::text))::json #> '{default}'::text[]) ->> 'read'::text))::boolean)));


create policy "surveys_read"
on "public"."surveyQuestions"
as permissive
for select
to authenticated
using ((isuseradmin(auth.uid()) OR (isuserinorg(organisation, auth.uid()) AND ((((getuserpermissionsobject(auth.uid(), 'surveys'::text))::json #> '{default}'::text[]) ->> 'read'::text))::boolean)));


create policy "surveys_read"
on "public"."surveys"
as permissive
for select
to authenticated
using ((isuseradmin(auth.uid()) OR (isuserinorg(organisation, auth.uid()) AND ((((getuserpermissionsobject(auth.uid(), 'surveys'::text))::json #> '{default}'::text[]) ->> 'read'::text))::boolean)));


create policy "notification_read"
on "public"."notifications"
as permissive
for select
to authenticated
using ((isuseradmin(auth.uid()) OR (isuserinorg(organisation, auth.uid()) AND notificationrecordexistsforuser(id, auth.uid()) AND (((type = 'news'::"NotificationType") AND ((((getuserpermissionsobject(auth.uid(), 'news'::text))::json #> '{default}'::text[]) ->> 'read'::text))::boolean) OR ((type = 'survey'::"NotificationType") AND ((((getuserpermissionsobject(auth.uid(), 'surveys'::text))::json #> '{default}'::text[]) ->> 'read'::text))::boolean) OR ((type = 'report'::"NotificationType") AND ((((getuserpermissionsobject(auth.uid(), 'organisationReports'::text))::json #> '{default}'::text[]) ->> 'read'::text))::boolean) OR (type = 'notification'::"NotificationType")))));



