drop policy "reportupdates_read" on "public"."reportUpdates";

drop policy "reports_read" on "public"."reports";

drop policy "userprofiles_read" on "public"."userProfiles";

drop policy "userstructures_read" on "public"."userStructures";

drop policy "users_read" on "public"."users";

drop view if exists "public"."usersManagement";

create table "public"."surveys" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."roles" drop column "accountSettings";

alter table "public"."roles" drop column "homeDashboard";

alter table "public"."roles" drop column "myReports";

alter table "public"."roles" drop column "profile";

alter table "public"."roles" drop column "report";

alter table "public"."roles" drop column "settings";

alter table "public"."roles" drop column "userProfile";

alter table "public"."roles" add column "organisationSettings" jsonb;

alter table "public"."roles" add column "surveys" jsonb;

alter table "public"."roles" add column "userReports" jsonb;

alter table "public"."roles" add column "userSearch" jsonb;

alter table "public"."roles" alter column "userManagement" drop not null;

CREATE UNIQUE INDEX surveys_pkey ON public.surveys USING btree (id);

alter table "public"."surveys" add constraint "surveys_pkey" PRIMARY KEY using index "surveys_pkey";

create or replace view "public"."usersManagement" as  SELECT u.id,
    u."lastLogin",
    u."applicationRole",
    u.organisation,
    u.status,
    u."loginMethod",
    up.name,
    up."idNumber",
    up."jobTitle",
    up."smallPhotoUrl",
    up.email,
    up."mobileNumber",
    r.name AS role,
    us.company,
    lower(up.name) AS "orderName",
    lower(up."jobTitle") AS "orderJobTitle",
    lower(us.company) AS "orderCompany",
    lower(r.name) AS "orderRole",
    lower(((((((((up.name || ' '::text) || up."idNumber") || ' '::text) || up."jobTitle") || ' '::text) || up.email) || ' '::text) || up."mobileNumber")) AS search,
    up."profileRating",
    up."photoUrl",
    up."employmentType"
   FROM (((users u
     JOIN "userProfiles" up ON ((u.id = up.id)))
     JOIN roles r ON ((u.role = r.id)))
     JOIN "userStructures" us ON ((u.id = us.id)));


grant delete on table "public"."surveys" to "anon";

grant insert on table "public"."surveys" to "anon";

grant references on table "public"."surveys" to "anon";

grant select on table "public"."surveys" to "anon";

grant trigger on table "public"."surveys" to "anon";

grant truncate on table "public"."surveys" to "anon";

grant update on table "public"."surveys" to "anon";

grant delete on table "public"."surveys" to "authenticated";

grant insert on table "public"."surveys" to "authenticated";

grant references on table "public"."surveys" to "authenticated";

grant select on table "public"."surveys" to "authenticated";

grant trigger on table "public"."surveys" to "authenticated";

grant truncate on table "public"."surveys" to "authenticated";

grant update on table "public"."surveys" to "authenticated";

grant delete on table "public"."surveys" to "service_role";

grant insert on table "public"."surveys" to "service_role";

grant references on table "public"."surveys" to "service_role";

grant select on table "public"."surveys" to "service_role";

grant trigger on table "public"."surveys" to "service_role";

grant truncate on table "public"."surveys" to "service_role";

grant update on table "public"."surveys" to "service_role";

create policy "reportupdates_read"
on "public"."reportUpdates"
as permissive
for select
to authenticated
using ((isuseradmin(auth.uid()) OR ((((((getuserpermissionsobject(auth.uid(), 'userReports'::text))::json #> '{default}'::text[]) ->> 'read'::text))::boolean AND ((auth.uid() = "user") OR (getreporterbyreportid(report) = auth.uid()))) OR (((((getuserpermissionsobject(auth.uid(), 'organisationReports'::text))::json #> '{default}'::text[]) ->> 'read'::text))::boolean AND isuserinorg(getorgbyreportid(report), auth.uid())))));


create policy "reports_read"
on "public"."reports"
as permissive
for select
to authenticated
using ((isuseradmin(auth.uid()) OR (((reporter = auth.uid()) AND ((((getuserpermissionsobject(auth.uid(), 'userReports'::text))::json #> '{default}'::text[]) ->> 'read'::text))::boolean) OR (isuserinorg(organisation, auth.uid()) AND ((((getuserpermissionsobject(auth.uid(), 'organisationReports'::text))::json #> '{default}'::text[]) ->> 'read'::text))::boolean))));


create policy "userprofiles_read"
on "public"."userProfiles"
as permissive
for select
to authenticated
using ((isuseradmin(auth.uid()) OR (isuserinorg(organisation, auth.uid()) AND ((id = auth.uid()) OR ((((getuserpermissionsobject(auth.uid(), 'userSearch'::text))::json #> '{default}'::text[]) ->> 'read'::text))::boolean OR ((((getuserpermissionsobject(auth.uid(), 'userManagement'::text))::json #> '{users}'::text[]) ->> 'read'::text))::boolean))));


create policy "userstructures_read"
on "public"."userStructures"
as permissive
for select
to authenticated
using ((isuseradmin(auth.uid()) OR (isuserinorg(getorgbyuserid(id), auth.uid()) AND ((id = auth.uid()) OR ((((getuserpermissionsobject(auth.uid(), 'userSearch'::text))::json #> '{default}'::text[]) ->> 'read'::text))::boolean OR ((((getuserpermissionsobject(auth.uid(), 'userManagement'::text))::json #> '{users}'::text[]) ->> 'read'::text))::boolean))));


create policy "users_read"
on "public"."users"
as permissive
for select
to authenticated
using ((isuseradmin(auth.uid()) OR (isuserinorg(organisation, auth.uid()) AND ((id = auth.uid()) OR ((((getuserpermissionsobject(auth.uid(), 'userSearch'::text))::json #> '{default}'::text[]) ->> 'read'::text))::boolean OR ((((getuserpermissionsobject(auth.uid(), 'userManagement'::text))::json #> '{users}'::text[]) ->> 'read'::text))::boolean))));
