name: migrations
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['src/**']
jobs:
  migrate_db:
    runs-on: ubuntu-latest
    environment: Prod
    continue-on-error: true
    permissions:
      contents: write
    env:
      supabase_db_url: ${{ secrets.SUPABASE_DB_URL }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }} 
      PROJECT_ID: ${{ vars.SUPABASE_DEVELOP_PROJECT_ID }} 
    steps:
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - uses: actions/checkout@v4
      - name: Pull changes
        run: supabase link --project-ref ${{env.PROJECT_ID}}
      - name: Pull changes
        run: supabase db pull --linked
      - uses: stefanzweifel/git-auto-commit-action@v5
      - name: Push changes
        run: supabase db push --db-url "$supabase_db_url"
  deploy:
    needs: [migrate_db]
    environment: Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}