name: database-restore

on: workflow_dispatch
    
jobs:
  restore:
      runs-on: ubuntu-latest
      environment: ${{ github.ref_name == 'main' && 'Prod' || 'develop' }}
      env:
        supabase_db_url: ${{ secrets.SUPABASE_DB_URL }}   # For example: postgresql://postgres:[YOUR-PASSWORD]@db.<ref>.supabase.co:5432/postgres
        database_restore_date: ${{ vars.DATABASE_RESTORE_DATE }} 
      steps:
        - uses: keithweaver/aws-s3-github-action@v1.0.0
          with:
            command: cp
            source: "s3://supabase/default/backups/${{ env.database_restore_date }}/backup.zip"
            destination: ./backup.zip
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws_region: us-east-1
            flags: --endpoint-url https://object.pscloud.io
        - uses: montudor/action-zip@v1
          with:
            args: unzip -qq backup.zip -d backup
        - name: Activate postgresql
          run: sudo systemctl start postgresql.service
        - name: ls
          run: cd backup && cd backup && ls 

        # - name: Restore
        #   run: psql -c "DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;"--file roles.sql --file schema.sql --command 'SET session_replication_role = replica' --file data.sql --dbname "$supabase_db_url"